name: Build and Deploy to Azure Functions
on:
  push:
    branches:
      - master

env:
  APPNAME: devops-susaluj-testfnnodejs6
  APPLICATIONPATH: "Application"
  RESOURCEGROUPNAME: devops-susaluj-testfnnodejs6-rg
  LOCATION: South Central US
  HOSTINGPLAN: devops-susaluj-testfnnodejs6
  STORAGEACCOUNTNAME: devopssusalujtestfnnstr
  APPINSIGHTSLOCATION: South Central US
  NODE_VERSION: '8.11.1'
  SUBSCRIPTIONID: 7489b9b9-8abe-4b02-a0d9-f09f368df55f
  SKU: Dynamic Y1

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # login to azure
    - name: Login to Azure
      uses: azure/login@v1
      continue-on-error: false
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    # Setup Node
    - name: Use Node ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Install dependancies and build app
      continue-on-error: false
      run: |
        cd Application
        npm install
    # Run Unit Tests
    - name: Run unit tests
      continue-on-error: false
      run: |
        cd Tests
        npm install
        gulp unittest
    - name: Make directories for artifact upload
      continue-on-error: false
      run: |
        mkdir buildartifacts
        mkdir deploymenttemplates
    # Archive build artifact
    - name: Archive Application
      uses: montudor/action-zip@v0.1.0
      with:
        args: zip -qq -r ./buildartifacts/Application.zip ./${{ env.APPLICATIONPATH }}
    # Uploading application to artifact store
    - name: Upload Application to Build Artifact
      continue-on-error: false
      uses: actions/upload-artifact@v2
      with:
        name: buildartifacts
        path: buildartifacts
    # Archive Arm template
    - name: Archive ArmTemplates
      uses: montudor/action-zip@v0.1.0
      with:
        args: zip -qq -r ./deploymenttemplates/ArmTemplates.zip ./ArmTemplates
    # Uploading Arm Template to artifact store
    - name: Upload Arm templates to Artifact
      continue-on-error: false
      uses: actions/upload-artifact@v2
      with:
        name: deploymenttemplates
        path: deploymenttemplates

  deploy:
    name: Deploy application to AKS
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Login to Azure
      uses: azure/login@v1
      continue-on-error: false
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: 'Install Azure Function App CLI'
      run: |
        sudo apt-get update
        sudo apt-get install azure-functions-core-tools-3
    - name: Download Build Artifact
      uses: actions/download-artifact@v2
      continue-on-error: false
      with:
        name: buildartifacts
        path: buildartifacts
    - name: Unzipping Build Artifact
      uses: montudor/action-zip@v0.1.0
      with:
       args: unzip -qq ./buildartifacts/Application.zip -d .
    - name: Download Arm Template
      uses: actions/download-artifact@v2
      continue-on-error: false
      with:
        name: deploymenttemplates
        path: deploymenttemplates
    - name: Unzipping ARM template
      uses: montudor/action-zip@v0.1.0
      with:
       args: unzip -qq ./deploymenttemplates/ArmTemplates.zip -d .
    - name: Deploy ARM Template
      uses: azure/CLI@v1
      continue-on-error: false
      with:
        inlineScript: |
          az group create --name "${{ env.RESOURCEGROUPNAME }}" --location "${{ env.LOCATION }}"
          az deployment group create --resource-group "${{ env.RESOURCEGROUPNAME }}" --template-file ./ArmTemplates/windows-functionapp-template.json --parameters functionAppName="${{ env.APPNAME }}" hostingPlanName="${{ env.HOSTINGPLAN }}" appInsightLocation="${{ env.APPINSIGHTSLOCATION }}" storageAccountName="${{ env.STORAGEACCOUNTNAME }}" sku="${{ env.SKU }}"
    # Deploy the Function app to Azure Functions 
    - name: 'Deploy to Azure Function'
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.APPNAME }}
        package: ${{ env.APPLICATIONPATH }}
    - name: Finalizing
      run: |
        echo -e "\033[1;32mPlease use Azure portal or Azure Functions Core Tools to fetch url with keys to invoke the Azure function(s)\033[m"
        echo "func azure functionapp list-functions ${{ env.APPNAME }} --show-keys"
        echo "It may take upto 10 minutes for the function list to update"
